Accepted all-item-types option, added ACL control, updated interface
biblibre/omeka-plugin-ItemDuplicateCheck pull request #6
Opened 2021-10-12 17:20 UTC by DBinaghi

Changes summary (rules logic has not been touched):
- adapted style to Omeka Classic version 3.0
- added explanations for adding/editing rules
- added "All types" option, as a rule could apply to all Items
- added confirm messages for adding/editing actions
- improved rule description on deleting rule
- added ACL control to limit access to the plugin configuration
- sorted element list
- fixed (https://github.com/biblibre/omeka-plugin-ItemDuplicateCheck/issues/8) issue
- updated readme and languages files (general, Italian and French)

In order to test confirm messages texts: create a dummy rule, then edit dummy rule, then delete dummy rule.
In order to test ACL control: login as user with level lower than admin.

2021-10-15 13:04 UTC, jajm commented
Thanks for adding changes summary in PR description, that will help a lot!
Let me know when it is ready for review

2021-10-18 07:43 UTC, jajm requested changes
Overall, changes are looking good!
There are only a few things to fix. If you can do that, I'll merge it asap

2021-10-18 07:43 UTC, jajm commented on ItemDuplicateCheckPlugin.php
> +        'admin_navigation_main'
As a general rule, please do not modify what doesn't need to be modified.
Removing the comma here is useless, and it adds noise to the PR

2021-10-18 07:43 UTC, jajm commented on views/admin/check/check.php
> +        <ul style="list-style-type: none; margin-left: 0; padding-left: 0";>
There is a `;` outside of the style attribute

2021-10-18 07:43 UTC, jajm commented on views/admin/check/check.php
> +                    <ul style="list-style-type: none";>
There is a `;` outside of the style attribute here too

2021-10-18 07:43 UTC, jajm commented on controllers/RulesController.php
> +            'sort' => ($show_element_set_headings ? 'alphaBySet' : 'alpha')
I think it's better to use `orderBySet` here, to let users be able to configure the order they want.

2021-10-18 07:43 UTC, jajm commented on controllers/RulesController.php
> +                asort($option);
I don't know what this is supposed to do, but for me it only emits PHP warnings. If I remove the block I don't see any change (except that there are no warnings anymore)

2021-10-18 07:43 UTC, jajm commented on languages/fr.po
> +msgstr[1] "Attention : %s doublons de cet contenu ont été trouvés !"
It should be 'ce contenu', not 'cet contenu'

2021-10-18 07:57 UTC, DBinaghi commented on ItemDuplicateCheckPlugin.php
> +        'admin_navigation_main'
No problem for me, of course, but I do think the comma after the last element is always useless, and is just ignored by the interpreter, so I normally don't add it.

2021-10-18 07:57 UTC, DBinaghi commented on views/admin/check/check.php
> +        <ul style="list-style-type: none; margin-left: 0; padding-left: 0";>
Thx

2021-10-18 07:58 UTC, DBinaghi commented on views/admin/check/check.php
> +                    <ul style="list-style-type: none";>
Thx

2021-10-18 08:00 UTC, DBinaghi commented on controllers/RulesController.php
> +            'sort' => ($show_element_set_headings ? 'alphaBySet' : 'alpha')
I am actually working on that: if "show element sets names" is not on, there's just a list of element names, I think it's clearer for user to let the user know which element set they belong to. I'll submit my idea asap.

2021-10-18 08:01 UTC, DBinaghi commented on controllers/RulesController.php
> +                asort($option);
Once elements groups are created, then sorting them alphabetically solves a problem: without that, using translated element names messes up with the order. I did not notice any warning in my version, could you copy/paste any of them to let me understand what's causing them?

2021-10-18 08:02 UTC, DBinaghi commented on languages/fr.po
> +msgstr[1] "Attention : %s doublons de cet contenu ont été trouvés !"
Thx (Google translator to blame, this time :))

2021-10-18 08:28 UTC, jajm commented on controllers/RulesController.php
> +                asort($option);
This is what I see on `/admin/item-duplicate-check/rules/add`:

```
Notice: Undefined index: item_type_name in /home/omeka/omeka/plugins/ItemDuplicateCheck/controllers/RulesController.php on line 92
Notice: Undefined index: element_set_name in /home/omeka/omeka/plugins/ItemDuplicateCheck/controllers/RulesController.php on line 94
Notice: Undefined index: element_name in /home/omeka/omeka/plugins/ItemDuplicateCheck/controllers/RulesController.php on line 95
Notice: Undefined index: item_type_name in /home/omeka/omeka/plugins/ItemDuplicateCheck/controllers/RulesController.php on line 92
Notice: Undefined index: element_set_name in /home/omeka/omeka/plugins/ItemDuplicateCheck/controllers/RulesController.php on line 94
Notice: Undefined index: element_name in /home/omeka/omeka/plugins/ItemDuplicateCheck/controllers/RulesController.php on line 95
Notice: Undefined index: item_type_name in /home/omeka/omeka/plugins/ItemDuplicateCheck/controllers/RulesController.php on line 92
Notice: Undefined index: element_set_name in /home/omeka/omeka/plugins/ItemDuplicateCheck/controllers/RulesController.php on line 94
Notice: Undefined index: element_name in /home/omeka/omeka/plugins/ItemDuplicateCheck/controllers/RulesController.php on line 95
Notice: Undefined index: item_type_name in /home/omeka/omeka/plugins/ItemDuplicateCheck/controllers/RulesController.php on line 92
Notice: Undefined index: element_set_name in /home/omeka/omeka/plugins/ItemDuplicateCheck/controllers/RulesController.php on line 94
Notice: Undefined index: element_name in /home/omeka/omeka/plugins/ItemDuplicateCheck/controllers/RulesController.php on line 95
```

2021-10-18 08:34 UTC, jajm commented on controllers/RulesController.php
> +                asort($option);
Note that the comment I made is not only about the sort. It is also about the block above that is not displayed here :)

2021-10-18 09:49 UTC, DBinaghi commented on controllers/RulesController.php
> +            'sort' => ($show_element_set_headings ? 'alphaBySet' : 'alpha')
After thinking about your comment, but also taking into consideration the possibility of admin wanting a different behaviour for this plugin as opposed to the site's default behaviour, I think the best option would be to introduce a config option (incidentally: there's no config page now, but I've created it as there's at least another two options that could be added) that allows to choose which Element List layout to use. What do you reckon?

2021-10-18 09:56 UTC, jajm commented on controllers/RulesController.php
> +            'sort' => ($show_element_set_headings ? 'alphaBySet' : 'alpha')
That would be great. But if you want to work on it, please do it in another pull request (create a new branch first). There are already several unrelated changes here. Let's merge these ones before adding something else ;)

2021-10-18 11:56 UTC, DBinaghi commented on controllers/RulesController.php
> +            'sort' => ($show_element_set_headings ? 'alphaBySet' : 'alpha')
Rolled back to original function, for this branch. It should be good for mergin, now. In the meantime, I'll be working on the other changes.

2021-10-18 11:57 UTC, DBinaghi commented on controllers/RulesController.php
> +                asort($option);
Rolled back to original function, for this branch

2021-10-20 07:15 UTC, merged